version: '3.5'
services:
  interpreter:
    build:
      context: .
      target: python-environment
    volumes:
      - ./src:/src

  gpu-interpreter:
    build:
      context: .
      dockerfile: gpu.Dockerfile
      target: python-environment
    volumes:
    - ./src:/src
